In [18]:
#What is a Python library? Why ^o we use Python libraries?
"""Code Reusability: 
Libraries contain pre-written code that can be reused in multiple projects, saving time and effort for developers.

Increased Efficiency:
By utilizing libraries, developers can leverage optimized algorithms and functionalities, leading to more efficient and faster development.

Specialized Functionality:
Python libraries often provide specialized functionalities for specific tasks such as data manipulation, scientific computing, web development, machine learning, and more.

Community Contributions: 
Python has a vibrant community of developers who contribute to various libraries, ensuring continuous improvement and availability of new features.

Integration:
Libraries allow for easy integration with other technologies and systems, making it simpler to incorporate Python into existing workflows."""

#What is the ^ifference between Numpy array an^ List?
"""Data Type: 
In Python lists, elements can be of different data types, while NumPy arrays are homogeneous, meaning all elements in the array must be of the same data type.

Performance:
NumPy arrays are more efficient in terms of memory usage and computation speed compared to Python lists, especially when dealing with large datasets. This is because NumPy arrays are implemented in C and optimized for numerical operations.

Functionality:
NumPy arrays offer a wide range of mathematical functions and operations that can be performed directly on the arrays, such as element-wise operations, matrix multiplication, and linear algebra operations. Python lists lack these built-in functionalities and require iteration for such operations.

Indexing and Slicing:
Both NumPy arrays and Python lists support indexing and slicing. However, NumPy arrays allow for more advanced indexing techniques, such as boolean indexing and fancy indexing, which can be more convenient and efficient for certain tasks.

Memory Usage:
NumPy arrays typically consume less memory compared to Python lists, especially when dealing with large datasets, due to their homogeneous nature and optimized storage."""

#3. Fin^ the shape, size an^ ^imension of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]
import numpy as np
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
shape=array.shape
size=array.size
dimensions=array.ndim
print("Shape of the array:",shape)
print("Size of the array:",size)
print("Number of dimensions of the array:",dimensions)

#4. Write python co^e to access the first row of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
first_row=array[0]
print("First row of the array:",first_row)

#5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
element=array[2,3]
print("Element at the third row and fourth column:",element)

#6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
#[[1,2,3,4]
#[5 6,7,8],
#[9,10,11,12]]
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
odd_indexed_elements=array[:,1::2]
print("All odd-indexed elements:")
print(odd_indexed_elements)


#7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
random_matrix=np.random.rand(3,3)
print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)

#8. Describe the difference between np.random.rand and np.random.randn?
"""np.random.rand:
Generates random numbers from a uniform distribution over the interval [0, 1).
The function takes the shape of the output array as arguments, specifying the dimensions of the output array directly.
Each element in the output array is an independent random value drawn from a uniform distribution between 0 and 1.
Syntax: np.random.rand(d0, d1, ..., dn), where d0, d1, ..., dn specify the dimensions of the output array.

np.random.randn:
Generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
The function takes the size of the output array as arguments, specifying the number of samples to draw from the standard normal distribution for each dimension.
Each element in the output array is an independent random value drawn from a standard normal distribution (Gaussian distribution with mean 0 and standard deviation 1).
Syntax: np.random.randn(d0, d1, ..., dn), where d0, d1, ..., dn specify the dimensions of the output array."""

#9. Write co^e to increase the ^imension of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
expanded_array=np.expand_dims(array,axis=0)
print("Original array shape:",array.shape)
print("Expanded array shape:",expanded_array.shape)
print("Expanded array:")
print(expanded_array)

#10. How to transpose the following array in NumPy?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
transposed_array_T =array.T
transposed_array_np=np.transpose(array)
print("Original array:")
print(array)
print("\nTransposed array using .T attribute:")
print(transposed_array_T)
print("\nTransposed array using np.transpose() function:")
print(transposed_array_np)

#11. Consider the following matrix:
#Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

A2=np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
B2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

index_wise_multiplication=A2*B2
matrix_multiplication = np.dot(A2, B2.T)
matrix_addition=A2+B2
matrix_subtraction=A2-B2
matrix_division=B2/A2
print("Index-wise multiplication:")
print(index_wise_multiplication)
print("\nMatrix multiplication:")
print(matrix_multiplication)
print("\nMatrix addition:")
print(matrix_addition)
print("\nMatrix subtraction:")
print(matrix_subtraction)
print("\nMatrix division:")
print(matrix_division)


#12. Which function in Numpy can be use^ to swap the byte or^er of an array?
array=np.array([1,256,65536], dtype=np.int32)
swapped_array=array.byteswap()
print("Original array:")
print(array)
print("\nSwapped array:")
print(swapped_array)

#13. What is the significance of the np.linalg.inv function?
"""Determinant Calculation: The calculation of the inverse matrix involves the determinant of the original matrix. If the determinant of the matrix is zero, it means that the matrix is singular, and its inverse does not exist. Hence, np.linalg.inv can also be used to determine if a matrix is singular.
Applications in Statistics, Optimization, and Machine Learning: Matrix inversion has various applications in statistics, optimization problems, and machine learning algorithms, such as linear regression, least squares, and principal component analysis (PCA)."""

#14. What does the np.reshape function do, and how is it used?
arr=np.array([1,2,3,4,5,6])
reshaped_arr=np.reshape(arr,(3,2))
print("Original array:")
print(arr)
print("\nReshaped array:")
print(reshaped_arr)

#15. What is broa^casting in Numpy?
A=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
B=np.array([10,20,30])
result=A+B
print("Array A:")
print(A)
print("\nArray B:")
print(B)
print("\nResult of broadcasting:")
print(result)


Shape of the array: (3, 4)
Size of the array: 12
Number of dimensions of the array: 2
First row of the array: [1 2 3 4]
Element at the third row and fourth column: 12
All odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]
Random 3x3 matrix with values between 0 and 1:
[[0.05216322 0.19880862 0.49214592]
 [0.72455598 0.77587928 0.86915775]
 [0.50305667 0.64990488 0.89457101]]
Original array shape: (3, 4)
Expanded array shape: (1, 3, 4)
Expanded array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array using .T attribute:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Transposed array using np.transpose() function:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Index-wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix subtraction:
[[0 0 0 0